### ISSUE TITLE
Undefined argument `failure_handler` in call to SyncProducer constructor

### ISSUE THREAD

**Issue by andrewparmet** [kickstarter/telekinesis#16]
`failure_handler` is undefined here: https://github.com/kickstarter/telekinesis/blob/master/lib/telekinesis/producer/sync_producer.rb#L23

This seems to be an innocent mistake left over from AsyncProducer; removing it from the constructor call fixes the problem.

**Comment by andrewparmet** [comment]
@blinsay bump?

**Comment by bradurani** [comment]
Encountered this as well

**Comment by bradurani** [comment]
PR with fix: https://github.com/kickstarter/telekinesis/pull/20

**Comment by andrewparmet** [comment]
https://github.com/kickstarter/telekinesis/pull/23
