### ISSUE TITLE
Request for ability to set custom executors

### ISSUE THREAD

**Issue by peakxu** [kickstarter/telekinesis#8]
As discussed in https://github.com/kickstarter/telekinesis/pull/7, I would like the ability to use a different `ExecutorService` than the default `newCachedThreadPool`. As recommended by @blinsay, it sounds like it might be best to pass in as an extra parameter to KCL.

**Comment by peakxu** [comment]
Looks like it got implemented on https://github.com/kickstarter/telekinesis/tree/custom_executor. Thanks for the quick turnaround, @blinsay! Will close once merged + published to Rubygems.

**Comment by blinsay** [comment]
I just released and pushed to Rubygems.

https://rubygems.org/gems/telekinesis/versions/3.1.0-java

Enjoy!

**Comment by peakxu** [comment]
Great, thank you.
